---
# tasks file for dist_check

- name: Clean up the old file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ping_ok_file_linux_rhel5 }}"
    - "{{ ping_ok_file_linux_rhel6 }}"
    - "{{ ping_ok_file_linux_rhel7 }}"
    - "{{ ping_ok_file_linux_rhel8 }}"

- name: Touch the file
  file:
    path: "{{ item }}"
    state: touch
  with_items:
    - "{{ ping_ok_file_linux_rhel5 }}"
    - "{{ ping_ok_file_linux_rhel6 }}"
    - "{{ ping_ok_file_linux_rhel7 }}"
    - "{{ ping_ok_file_linux_rhel8 }}"

- name: Check ssh version the ping_result file for Linux
  shell: while read ips; do export ips_target=${ips} ; bash -c "if [ `head -n1 < /dev/tcp/${ips_target}/22 | awk -F '_' '{print $(NF)}' | awk -v ssh_version=7.4 '{print($1==ssh_version)?"1":"0"}'` -eq '1' ]; then echo ${ips_target} >> {{ ping_ok_file_linux_rhel7 }} ; elif [ `head -n1 < /dev/tcp/${ips_target}/22 | awk -F '_' '{print $(NF)}' | awk -v ssh_version=6.6.1 '{print($1==ssh_version)?"1":"0"}'` -eq '1' ]; then echo ${ips_target} >> {{ ping_ok_file_linux_rhel7 }} ; elif [ `head -n1 < /dev/tcp/${ips_target}/22 | awk -F '_' '{print $(NF)}' | awk -v ssh_version=5.3 '{print($1==ssh_version)?"1":"0"}'` -eq '1' ]; then echo ${ips_target} >> {{ ping_ok_file_linux_rhel6 }} ; elif [ `head -n1 < /dev/tcp/${ips_target}/22 | awk -F '_' '{print $(NF)}' | awk -v ssh_version=4.3 '{print($1==ssh_version)?"1":"0"}'` -eq '1' ]; then echo ${ips_target} >> {{ ping_ok_file_linux_rhel5 }} ; elif [ `head -n1 < /dev/tcp/${ips_target}/22 | awk -F '_' '{print $(NF)}' | awk -v ssh_version=7.8 '{print($1==ssh_version)?"1":"0"}'` -eq '1' ]; then echo ${ips_target} >> {{ ping_ok_file_linux_rhel8 }} ;fi &" ; done < {{ ping_ok_file_linux }}
  changed_when: false

- name: The path of Result file
  debug:
    msg:
      - "ping_ok for Linux file (RHEL5) is in '{{ ping_ok_file_linux_rhel5 }}'"
      - "ping_ok for Linux file (RHEL6) is in '{{ ping_ok_file_linux_rhel6 }}'"
      - "ping_ok for Linux file (RHEL7) is in '{{ ping_ok_file_linux_rhel7 }}'"
      - "ping_ok for Linux file (RHEL8) is in '{{ ping_ok_file_linux_rhel8 }}'"

